########################################################################
	
	# Outlook Signature Client Side Script
	
	# Author: Michael Poff
	
	# Purpose: Takes the signatures generated by the creation tool
	# and places them on in the appropriate folder on the users 
	# workstation
	
	# Usage: 

########################################################################

try
{
$curr_user = [Environment]::UserName
$comp_name = [Environment]::MachineName
$sig_path_client = "C:\Users\$curr_user\AppData\Roaming\Microsoft\Signatures\"
$sig_path_server = "\\ams-dc01\Deployment\EmailSig\sigvault\$curr_user\"
$Log_Path = "\\ams-dc01\deployment\EmailSig\Logs\$curr_user\"
$Now = Get-Date -format "dd MMM yyyy hh:mm tt"
$srvr_upchck = "\\ams-dc01\Deployment\EmailSig\Resources\srvr_upchck.txt" 
$client_upchck = "C:\Users\$curr_user\AppData\Roaming\Microsoft\Signatures\srvr_upchck.txt"



#Is there a matching signature on the client?
Write-Host "============================================================="
Write-Host "Checking For Existing Signature For $curr_user On: $comp_name"
Write-Host "============================================================="
	
	#If not create the requisite folder/path.
	if ((test-path -path $sig_path_client) -eq $false ) 
	{
	New-Item -ItemType Directory -Path $sig_path_client
	Write-Host "========================="
	Write-Host "Creating Signature Folder"
	Write-Host "========================="
	}
	#Otherwise do nothing.
	else
	{
	Write-Host "======================"
	Write-Host "Signature Folder Found"
	Write-Host "======================"
	}

#Is there a newer version of the signature on the server?

Write-Host "============================================"
Write-Host "Checking Server for new version of signature"
Write-Host "============================================"

#Pull the date from the server and the client
$srvr_date = Get-Content $srvr_upchck -Raw
$client_date = Get-Content $client_upchck -Raw


#Compare the server and client dates.

#If the server date is newer than the client date copy from server
If ($srvr_date -gt $client_date)
{	
Write-Host "============================="
Write-Host "Copying Signature From Server"
Write-Host "============================="

	#Check if there is a signature on the server for the user.
	
	#If not throw an error
	If ((test-path -path $sig_path_server) -eq $false)
	{
	Write-Host ""
	Write-Host ""
	Write-Host ""
	Write-Host "ERROR: No Signature Exists on the Server for $curr_user"
	}
	
	#If so copy it over
	ElseIf ((test-path -path $sig_path_server) -eq $true)
	{
	# Copy actual files that make up signature
	Remove-Item $sig_path_client -recurse
	Copy-Item "\\server\Deployment\EmailSig\sigvault\$curr_user\" $sig_path_client
	Copy-Item "\\server\Deployment\EmailSig\sigvault\$curr_user\*" -recurse $sig_path_client
	Copy-Item $srvr_upchck $client_upchck
	Write-Output "============================="
	Write-Output "Signature Copied Successfully"
	Write-Output "============================="
	}
	
	#For debugging
	#Else
	#{
	#Write-Output "ERROR: Signature Could Not Copy. Specified Signature Already Exists"
	#}
}
#If the server date is older or the same as the client, present the message.
Else
	{
	Write-Host "============================================"
	Write-Host "Client Has Most Current Version of Signature"
	Write-Host "============================================"
	}
}
Catch
{
Read-Host -Prompt "Press Enter"
}
	
